### ISSUE TITLE
Search highlight hides result

### ISSUE THREAD

**Issue by rm-code** [anson0370/base16-ocean-dark-syntax-theme#3]
Hey @anson0370,

there seems to be a small issue while using the search function with your syntax theme:
![screenshot 2015-12-01 22 44 39](https://cloud.githubusercontent.com/assets/11627131/11515556/d4ab377c-987e-11e5-932d-5af8f82fe2b8.png)
As you can see it hides the search results in the editor.

Btw. I created a [base16 ocean dark ui-theme](https://github.com/rm-code/base16-ocean-dark-ui) :blush:

**Comment by anson0370** [comment]
Thx. I'll check this as soon as I off duty today.

And your ui theme looks great. I'm going to try it. :smile:

**Comment by rm-code** [comment]
Much appreciated! I tried to fix it on my own fork ... but I didn't manage to do it. It's just a small issue anyway :grinning:

**Comment by anson0370** [comment]
What's the versions of your Atom and this syntax theme? And is there only the .less files have this issue? Coz I can't reproduce it.

**Comment by rm-code** [comment]
- Atom Version:  1.3.0-beta6 (I can reproduce it with Atom 1.2.4 as well)
- UI Version: 0.1.5
- OS: OSX 10.10.5

**Comment by rm-code** [comment]
- Atom Version:  1.3.0-beta6 (I can reproduce it with Atom 1.2.4 as well)
- UI Version: 0.1.5
- OS: OSX 10.10.5

As far as I can tell the issue happens on all files I am using. What UI-Theme do you use?

**Comment by anson0370** [comment]
Oh I can reproduce it now! With search something and then click one of the match strings. Working on it.

**Comment by anson0370** [comment]
Fixed temporary. I think I should rebuild this theme from the official template-syntax package. This package is too old and many class and dom changes.

**Comment by rm-code** [comment]
Thanks :+1:
