### ISSUE TITLE
Remove gradient in gutter line numbers

### ISSUE THREAD

**Issue by jordwalke** [anson0370/base16-ocean-dark-syntax-theme#6]
The gradient over the line numbers looks really distracting. Could you please remove it from the default?

**Comment by anson0370** [comment]
@rm-code Maybe u and @jordwalke can discuss about this? Coz this is not my idea. :smile:

**Comment by rm-code** [comment]
Well if someone finds it distracting I guess it can be removed. I'll just keep it in my personal theme then :grin:

**Comment by jordwalke** [comment]
Is there a way to use a config setting?
(Apologies if you consider this a critique of your personal style - it's just that with my UI Theme that I use, there are no other gradients so it looks out of place.)

**Comment by anson0370** [comment]
@jordwalke I don't know there is a simple way to have a config setting for a syntax theme. (It's possible to have a config setting for UI themes or plugins.) So I will remove the gradient from my repository and @rm-code can keep it personal.

We can fix this once Atom support settings view for syntax themes I guess. :smile:

**Comment by anson0370** [comment]
Just revert and publish a new version. And thank you @rm-code again.

**Comment by rm-code** [comment]
> (Apologies if you consider this a critique of your personal style - it's just that with my UI Theme that I use, there are no other gradients so it looks out of place.)

No worries :smile:
