### ISSUE TITLE
Theme is broken since 0.1.10

### ISSUE THREAD

**Issue by rm-code** [anson0370/base16-ocean-dark-syntax-theme#9]
![screenshot 2017-01-14 01 29 36](https://cloud.githubusercontent.com/assets/11627131/21950230/077bc588-d9f9-11e6-946c-b977d015fd90.png)

Looks like the changes introduced in #8 caused the theme to break on my end. Can you reproduce the issue on your end too?

When I pick a different syntax theme it works fine.

**Comment by rm-code** [comment]
cc @prurph

**Comment by prurph** [comment]
![image](https://cloud.githubusercontent.com/assets/6109531/21950544/1796beca-d9ca-11e6-83fd-06aba12d721e.png)

That's odd--I'm not noticing that issue. Does it happen in Atom v1.13.0 as well? I notice you seem to be using beta there?

When I look at the inspector on my end I see the parts that are incorrectly white on your screenshot there are being set to dark on mine by the selector `atom-pane-container atom-pane .item-views .pane-item` which this syntax package doesn't include.

**Comment by prurph** [comment]
Okay it looks fine on atom beta v1.14.0 for me as well:

![image](https://cloud.githubusercontent.com/assets/6109531/21950733/dbb81ee2-d9cb-11e6-8c2f-cc7e42950f71.png)

I even tried with OS X dark UI on just in case and it looked okay. Are you on Sierra? I'm still running El Cap.

**Comment by rm-code** [comment]
> When I look at the inspector on my end I see the white parts there are being set by atom-pane-container atom-pane .item-views .pane-item which this syntax package doesn't seem to include.

Yeah, that's actually something my UI-Theme should handle ... that's why I was so confused when it fixed itself as soon as I picked a different syntax theme.

I checked it with the non-beta version as well and it looks the same:
![screenshot 2017-01-14 02 03 22](https://cloud.githubusercontent.com/assets/11627131/21950682/c99913f6-d9fd-11e6-856b-04dc1adee697.png)

It's probably just something bad going on with my own installation (or rather the .atom folder). 

I'll see if I can fix it and report back later :+1:

EDIT: Also running on El Capitan.

**Comment by prurph** [comment]
Okay cool, keep me updated and I'll keep playing around here to see if I can figure anything out.

Toggling the syntax highlighting on the settings page for me has zero effect regardless of whether I'm using your ui-theme or any other so it seems (not surprisingly) that the syntax theme shouldn't have any say on that page's appearance so there's definitely something weird going on here.

**Comment by rm-code** [comment]
I just removed the compile-cache folder and now everything is back to normal. What a strange thing to happen...

Anyway, thanks for the quick reply and the update for 1.13 👍

**Comment by prurph** [comment]
Great! Glad it's straightened out, and obviously I love your UI theme!

**Comment by rm-code** [comment]
Thanks! Much appreciated :)
